apiVersion: v1
items:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewBuild
    creationTimestamp: null
    labels:
      build: calrissian
    name: calrissian
  spec:
    lookupPolicy:
      local: true
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewBuild
    creationTimestamp: null
    labels:
      build: calrissian
    name: calrissian
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: calrissian:latest
    postCommit: {}
    resources: {}
    source:
      git:
        ref: 40-packaging-python-official-base
        uri: https://github.com/Duke-GCB/calrissian.git
      type: Git
    strategy:
      type: Docker
    triggers:
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
kind: List
metadata: {}
